# Generated by Django 6.0.2 on 2026-03-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('location', models.CharField(default='г.Казань, пр-кт Ибрагимова, д.44 Спортивный Комплекс «Батыр»', max_length=300, verbose_name='Место проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('registration_deadline', models.DateField(verbose_name='Дедлайн регистрации')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('club', models.CharField(max_length=200, verbose_name='Клуб/Школа')),
                ('coach', models.CharField(blank=True, max_length=200, verbose_name='Тренер')),
                ('age_category', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Возрастная категория')),
                ('weight_category', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Весовая категория')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(max_length=20, verbose_name='Возрастная категория')),
                ('weight_category', models.CharField(max_length=50, verbose_name='Весовая категория')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('round_name', models.CharField(default='1/8', max_length=50, verbose_name='Раунд')),
                ('round_number', models.IntegerField(default=1, verbose_name='Номер раунда')),
                ('score_p1', models.IntegerField(default=0, verbose_name='Счет участника 1')),
                ('score_p2', models.IntegerField(default=0, verbose_name='Счет участника 2')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('walkover', 'Неявка')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('match_order', models.IntegerField(default=0, verbose_name='Порядок матча')),
                ('is_third_place_match', models.BooleanField(default=False, verbose_name='Бой за 3 место')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.match', verbose_name='Следующий матч')),
                ('participant1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='tournament.participant', verbose_name='Участник 1')),
                ('participant2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='tournament.participant', verbose_name='Участник 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournament.participant', verbose_name='Победитель')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Поединок',
                'verbose_name_plural': 'Поединки',
                'ordering': ['age_category', 'gender', 'weight_category', 'round_number', 'match_order'],
            },
        ),
    ]
