# Generated by Django 6.0.2 on 2026-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='row_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер строки в файле'),
        ),
        migrations.AddField(
            model_name='participant',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Файл-источник'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн регистрации'),
        ),
    ]
