# Generated by Django 6.0.2 on 2026-03-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_participant_row_number_participant_source_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='third_place_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_sources', to='tournament.match', verbose_name='Бой за 3 место'),
        ),
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournament.match', verbose_name='Следующий матч'),
        ),
    ]
